background {
    monitor =
    path = screenshot   # takes a screenshot and blurs it
    blur_passes = 3
    blur_size = 7
}

# Moving shape to prevent burn-in
shape {
    monitor =
    size = 360, 60
    color = rgba(255, 255, 255, 0.1)
    rounding = -1
    border_size = 0
    rotate = 0
    
    position = 0, 80
    halign = center
    valign = center
    
    # This makes it move around
    animation {
        on = true
        bezier = linear, 0, 0, 1, 1
        animation = moveX, 20, 2, linear, loop
        animation = moveY, 30, 2.5, linear, loop
    }
}

label {
    monitor =
    text = cmd[update:1000] echo "$(date +"%H:%M")"
    color = rgba(255, 255, 255, 0.6)
    font_size = 120
    font_family = JetBrains Mono
    
    position = 0, -200
    halign = center
    valign = top
}
