
################
### MONITORS ###
################

# See https://wiki.hypr.land/Configuring/Monitors/
monitor=,2880x1800@120,auto,auto
monitor=HDMI-A-1,2560x1440,auto,auto
monitor=HDMI-A-2,2560x1440,auto,auto
